using System.Linq;
using Content.Client._Starlight.Silicons.Borgs; // Starlight-edit
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared.Guidebook;
using Content.Shared.Silicons.Borgs;
using Content.Shared.Silicons.Borgs.Components;
using Content.Shared._Starlight.Silicons.Borgs; // Starlight-edit
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects; // Starlight-edit
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility; // Starlight-edit

namespace Content.Client.Silicons.Borgs;

/// <summary>
/// Menu used by borgs to select their type.
/// </summary>
/// <seealso cref="BorgSelectTypeUserInterface"/>
/// <seealso cref="BorgSwitchableTypeComponent"/>
[GenerateTypedNameReferences]
public sealed partial class BorgSelectTypeMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entManager = default!; // Starlight-edit
    private readonly SpriteSystem _spriteSystem = default!; // Starlight-edit

    private BorgTypePrototype? _selectedBorgType;

    private BorgPaintPrototype? _selectedBorgPaint; // Starlight-edit

    public event Action<(ProtoId<BorgTypePrototype>, ProtoId<BorgPaintPrototype>)>? ConfirmedBorgType; // Starlight-edit

    private static readonly List<ProtoId<GuideEntryPrototype>> GuidebookEntries = new() { "Cyborgs", "Robotics" };

    public BorgSelectTypeMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entManager.System<SpriteSystem>(); // Starlight-edit

        ConfirmTypeButton.OnPressed += ConfirmButtonPressed;
        HelpGuidebookIds = GuidebookEntries;
    }

    // Starlight-start: Setup menu with available borg types and paints
    public void SetupMenu(EntityUid owner)
    {
        if (!_entManager.TryGetComponent<BorgSwitchableTypeComponent>(owner, out var switchableType))
            return;

        var group = new ButtonGroup();
        if (switchableType.AvailableTypes.Any())
        {
            foreach (var borgTypeId in switchableType.AvailableTypes)
            {
                if (!_prototypeManager.TryIndex<BorgTypePrototype>(borgTypeId, out var borgType))
                    continue;

                var button = new Button
                {
                    Text = PrototypeName(borgType),
                    Group = group,
                };
                button.OnPressed += _ =>
                {
                    //_selectedBorgType = borgType; Already added at UpdateInformation
                    UpdateInformation(borgType);
                };
                SelectionsContainer.AddChild(button);
            }
        }
        else
        {
            foreach (var borgType in _prototypeManager.EnumeratePrototypes<BorgTypePrototype>().OrderBy(PrototypeName))
            {
                var button = new Button
                {
                    Text = PrototypeName(borgType),
                    Group = group,
                };
                button.OnPressed += _ =>
                {
                    //_selectedBorgType = borgType; Already added at UpdateInformation
                    UpdateInformation(borgType);
                };
                SelectionsContainer.AddChild(button);
            }
        }
    }
    // Starlight-end

    private void UpdateInformation(BorgTypePrototype prototype)
    {
        var oldSelectedType = _selectedBorgType; // Starlight-edit
        _selectedBorgType = prototype;

        InfoContents.Visible = true;
        InfoPlaceholder.Visible = false;

        // Starlight-start: Borg Paints
        if (IsFirstUpdate(oldSelectedType, prototype)
            && prototype.BasicPaint != null
            && _prototypeManager.TryIndex<BorgPaintPrototype>(prototype.BasicPaint, out var basicPaint))
            _selectedBorgPaint = basicPaint;

        if (_selectedBorgPaint == null || !_selectedBorgType.Paints.Contains(_selectedBorgPaint))
            ConfirmTypeButton.Disabled = true;
        else
            ConfirmTypeButton.Disabled = false;
        // Starlight-end

        NameLabel.Text = PrototypeName(prototype);
        DescriptionLabel.Text = Loc.GetString($"borg-type-{prototype.ID}-desc");
        ChassisView.SetPrototype(prototype.DummyPrototype);

        // Starlight-start: Borg Paints
        if (!IsFirstUpdate(oldSelectedType, prototype))
            return;

        PaintContents.RemoveAllChildren();
        var paintGroup = new ButtonGroup();
        foreach (var borgPaint in prototype.Paints)
        {
            if (!_prototypeManager.TryIndex<BorgPaintPrototype>(borgPaint, out var borgPaintPrototype))
                continue;

            var name = borgPaintPrototype.Name ?? borgPaintPrototype.ID;

            if (borgPaintPrototype.Price != null && borgPaintPrototype.Price > 0)
                name += $" ({borgPaintPrototype.Price}₡)";

            var paintButton = new BorgPaintButton(_spriteSystem, new SpriteSpecifier.Rsi(new ResPath(borgPaintPrototype.SpritePath), borgPaintPrototype.SpriteBodyState), name, false)
            {
                Group = paintGroup,
            };
            paintButton.OnPressed += _ =>
            {
                _selectedBorgPaint = borgPaintPrototype;
                if (_selectedBorgType != null)
                    UpdateInformation(_selectedBorgType);
            };

            if (borgPaint.Id == prototype.BasicPaint)
                paintButton.Pressed = true;

            PaintContents.AddChild(paintButton);
        }
        // Starlight-end
    }

    private void ConfirmButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        if (_selectedBorgType == null || _selectedBorgPaint == null || !_selectedBorgType.Paints.Contains(_selectedBorgPaint)) // Starlight-edit
            return;

        ConfirmedBorgType?.Invoke((_selectedBorgType, _selectedBorgPaint)); // Starlight-edit
    }

    private static string PrototypeName(BorgTypePrototype prototype)
    {
        return Loc.GetString($"borg-type-{prototype.ID}-name");
    }

    private bool IsFirstUpdate(BorgTypePrototype? oldProto, BorgTypePrototype newProto) => oldProto == null || oldProto.ID != newProto.ID; // Starlight-edit
}
